version: "2.1"

services:

    elasticsearch:
        container_name: elasticsearch
        build:
            context: elasticsearch/
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        expose:
            - "9200"
            - "9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - support
        healthcheck:
            test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
            interval: 30s
            timeout: 10s
            retries: 5


    logstash:
        container_name: logstash
        build:
            context: logstash/
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
            - "5000:5000"
            - "8345:8345"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - support
        depends_on:
            elasticsearch:
                condition: service_healthy

    kibana:
        container_name: kibana
        build:
            context: kibana/
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5601:5601"
        networks:
            - support
        depends_on:
            elasticsearch:
                condition: service_healthy

    prometheus:
        container_name: prometheus
        build:
            context: prometheus/
        volumes:
            - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./prometheus/config/instances.json:/etc/prometheus/instances.json:ro
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - support

networks:
    support:
        driver: bridge
